name: Bug报告
labels:
  - bug
assignees:
  - IlyaIvanovsky
description: 报告漏洞
body:
  - type: dropdown
    id: modloader
    attributes:
      label: 模组加载器
      options:
        - Forge（推荐）
        - Fabric
        - Quilt
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft版本
      placeholder: "例如1.19.4"
    validations:
      required: true
  - type: input
    id: modloader-version
    attributes:
      label: 模组加载器版本
      description: |
        模组加载器的版本
        如果使用Fabric（不推荐），你也要说明Fabric API的版本。
      placeholder: 例如Forge 45.0.64
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: No Chat Reports模组版本
      placeholder: 例如1.19.4-2.1.3
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: 整合包信息
      description: |
        仅在使用整合包的时候才提供此信息。
  - type: input
    attributes:
      label: "日志"
      description: |
       latest.log文件
  - type: textarea
    attributes:
      label: Bug描述
      placeholder: 描述漏洞。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 重现步骤
      description: |
        怎样做，就会出现这个Bug？
      placeholder: |
        1. First step
        2. Second step
        3. etc...
  - type: textarea
    attributes:
      label: 其他信息
      description: |
        一些其他的信息。
