license="WTFPL"
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Aizistral-Studios/No-Chat-Reports/issues"
[[mods]]
modId="nochatreports"
version="1.19.4-v2.1.3"
displayName="No Chat Reports"
displayURL="https://www.curseforge.com/minecraft/mc-mods/no-chat-reports"
logoFile="assets/nochatreports/textures/misc/NCR_logo.png"
credits="Madis0 (aka robotkoer)"
authors="Aizistral"
description='''
Strips cryptographic signatures from player messages, making it impossible to track and associate them with your Mojang/Microsoft account, as well as use Player Chat Reporting feature.
'''
[[dependencies.nochatreports]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nochatreports]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,)"
    ordering="NONE"
    side="BOTH"